name: Releases
on:
  push:
    tags:
      - "*"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - uses: actions-rs/cargo@v1
        with:
          command: build
          args: --release
      - uses: ncipollo/release-action@v1
        with:
          artifacts: "target/release/g14-perf-control"
          token: ${{ secrets.GITHUB_TOKEN }}
